"""empty message

Revision ID: e6e06b564d4e
Revises: 53e095e18f8a
Create Date: 2025-02-13 11:25:57.048812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e06b564d4e'
down_revision = '53e095e18f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comic', schema=None) as batch_op:
        batch_op.drop_constraint('comic_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'character', ['character_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comic', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comic_ibfk_1', 'character', ['character_id'], ['id'])

    # ### end Alembic commands ###
